### PR TITLE
Add MissionControl profile

### PR DESCRIPTION
**Pull request by MissionControlValidator**

### CODE REVIEW

**Comment by MissionControlValidator** [comment]
terravaloper1x4ce4fhqdnu8j7hrp64qmthumsvuhlq8y0kvx4 is our Terra Classic validator address

terravaloper1sextn6xd46edrc02tf6d2fysmqw62qu7ng3kkm is our Terra2 validator address

In this PR we have made some changes to our Terra Classic profile too since it was outdated

**Review by terran6 — CHANGES_REQUESTED** [review]
Well, your Terra Classic validator (terravaloper1x4ce4fhqdnu8j7hrp64qmthumsvuhlq8y0kvx4) info is in a folder that doesn't correspond with the address.  I would just move it over to a folder with the equivalent name.  Then I can merge your information.

**Comment by MissionControlValidator** [comment]
It is our classic validator address, check here: https://finder.terra.money/classic/validator/terravaloper1x4ce4fhqdnu8j7hrp64qmthumsvuhlq8y0kvx4

**Review by terran6 — COMMENTED** [review]
The new files which were added, apparently holding your Terra 2.0 terravaloper address, are inside a file with your Terra Classic terravaloper address.  Please see below for details:

terravaloper_discrepancy

**Comment by MissionControlValidator** [comment]
Fixed now, sorry for the problem

**Comment by terran6** [comment]
No problem, thanks for the fix!

**Pull request merged**
