### PR TITLE
Add profile validation

### LINKED ISSUE #50: Some validators have malformated profile.json
[Example](https://github.com/terra-project/validator-profiles/blob/master/validators/terravaloper175hhkyxmkp8hf2zrzka7cnn7lk6mudtv4uuu64/profile.json) -> trailing comma

### PR DESCRIPTION
**Pull request by etienne-napoleone**
Run [ajv](https://github.com/ajv-validator/ajv-cli) on new PRs against the schema at `ci/profiles-schema.json` on all validators `profile.json`.

Might be good to add a branch protection rule on master to require status check to pass!

Before merging, current errors should be fixed (or json schema adapted):

```
validators/terravaloper103ra79dl2un2ltknhyz7crm5y29g4vhmycfwv9 copy/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'telegram' },
    message: "should have required property 'telegram'"
  }
]
validators/terravaloper103ra79dl2un2ltknhyz7crm5y29g4vhmycfwv9/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'telegram' },
    message: "should have required property 'telegram'"
  }
]
validators/terravaloper13kcwnlafvu4xvy2jr3vhdte9aq9tadwds3lx2d/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'telegram' },
    message: "should have required property 'telegram'"
  }
]
validators/terravaloper15s5d4lm0n75af9jxwawqzl73trnrypdslajxz4/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'telegram' },
    message: "should have required property 'telegram'"
  }
]
validators/terravaloper175hhkyxmkp8hf2zrzka7cnn7lk6mudtv4uuu64/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'telegram' },
    message: "should have required property 'telegram'"
  }
]
validators/terravaloper1audgfvmgt0js54p3s8kj3r40uwej6vy2tv6rrw/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'email' },
    message: "should have required property 'email'"
  }
]
validators/terravaloper1jsdfyz8uhw2nd7cl45709w40r268phmvxam8eh/profile.json invalid
[
  {
    keyword: 'required',
    dataPath: '.contact',
    schemaPath: '#/properties/contact/required',
    params: { missingProperty: 'telegram' },
    message: "should have required property 'telegram'"
  }
]
```

Closes #50

### CODE REVIEW

**Comment by hanjukim** [comment]
@ouiliame Can we remove telegram from required fields? Test is failing because of it.

**Comment by hanjukim** [comment]
@ouiliame Also empty field ("email": "", "telegram": "") is valid.

**Comment by ouiliame** [comment]
@etienne-napoleone Could you also make add CI that runs `python3 ci/regenerate.py` once merged on master

**Comment by etienne-napoleone** [comment]
@ouiliame will do later when I have time in another pr, please open an issue

**Comment by Jared-Warn** [comment]
no action since october 2020

**Pull request closed without merging**
