### PR TITLE
New Hermes Protocol profile

### PR DESCRIPTION
**Pull request by Chinoman10**
Submit the Terra Validators profile for **Hermes Protocol**.

### CODE REVIEW

**Review by terran6 — CHANGES_REQUESTED** [review]
The wallet address under "Validator:" at the top of the README does not need to be included.  Please provide your Terravaloper address (terravaloper1g6pwngzfj73wnxm7y5gae0thylphugumc96gh3) at the top of the README as per the [README template](https://github.com/terra-money/validator-profiles/blob/master/template/README.md).  Thanks!

**Comment by Chinoman10** [comment]
@terran6 we've made the requested change.
Thanks.

**Review by terran6 — APPROVED** [review]

**Comment by Chinoman10** [comment]
Hey @terran6 we just noticed that we forgot to update the front page README.md that has the list of all submitted validators.
Should we submit a new PR for this, or will you guys do that?

**Comment by terran6** [comment]
@Chinoman10 that should be updated automatically.

**Comment by Chinoman10** [comment]
> @Chinoman10 actually you will have to submit a PR for this. I'll merge it in whenever you can push it up. Thanks!

Done : #490

**Pull request merged**
