### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by thvalidators**

### CODE REVIEW

**Comment by thvalidators** [comment]
Change by terra6 request

**Comment by terran6** [comment]
> Change by terra6 request

@thvalidators Did you mean to close the other PR?  This PR has no changes inside 😅.

Hopefully, you can get your validator up and running so that your `terravaloper` can be searched for on https://finder.terra.money/ using the network on which you guys are launching.

Let me know if you have any problems along the way.

**Comment by thvalidators** [comment]
Please find the address in terra classic

**Comment by thvalidators** [comment]
> Please find the address in terra classic



> 

Please find the address in terra classic

**Review by terran6 — APPROVED** [review]
🎉

**Comment by thvalidators** [comment]
Hi, developer

I have some trouble and questions to ask
1. I do the wrong max commission %. I needed to set it to 5% but now it
showed up 100%. Do you have any way to help me change?
2. I have set up validator version v0.5.22 without oracle, how can i add
oracle?

could you please help me to figure it out or give any advice

best regards,


ในวันที่ ศ. 28 ต.ค. 2022 เวลา 11:03 Manuel Alessandro Collazo <
***@***.***> เขียนว่า:

**Comment by Jared-TFL** [comment]
There is no way to change the max commission.
You'll have to start a new validator.

**Comment by thvalidators** [comment]
Thank you for answering my questions.

May i ask another question? my uptime % is continuous decrease so, i would
like to know the reason for decrease.

Thank you

ในวันที่ ศ. 18 พ.ย. 2022 เวลา 21:25 Jared ***@***.***>
เขียนว่า:

**Pull request merged**
