### PR TITLE
update Bit Cat validator email&intro info

### PR DESCRIPTION
**Pull request by wjdfx**

### CODE REVIEW

**Review by terran6 — CHANGES_REQUESTED** [review]
Hey @wjdfx!  Do you mind updating the email inside of the `profile.json` file in your validator directory as well if it needs to be changed?  Thanks!

**Comment by wjdfx** [comment]
@terran6 Thanks for you reminder. I have updated that as well.

**Review by terran6 — APPROVED** [review]
Perfect 👍🏼

**Review by MKaslan1-creta — COMMENTED** [review]
MKaslan1

**Pull request merged**
