### PR TITLE
Th validators profile

### PR DESCRIPTION
**Pull request by thvalidators**
Terra Validators from Thailand by Mediacenter

### CODE REVIEW

**Review by terran6 — CHANGES_REQUESTED** [review]
Hello!  It seems as though your README does not contain relevant information about your validator, but is actually the README for the `terra-money/validator-profiles` repo.  Maybe you can take a look at other READMEs available for other validators and get an idea of what information may be valuable to put in there.  Thanks!

**Review by terran6 — CHANGES_REQUESTED** [review]
Please remove the logo, outlined in red, as it is outside of your validator directory.  The two logo files in orange seem to be the same image, please choose one and delete the other.

duplicate_logos

**Review by terran6 — CHANGES_REQUESTED** [review]
Still need to remove the `avatar.png` file outside of your validator directory.  I was not able to find your `terravaloper` address, `terravaloper1uyu9sx8q5lmsdrj4t8w0unvd2u2uudq2kwpuxu`, on Mainnet or Classic.  Can you confirm that this address is correct?  On which network are you launching?  Thanks!

**Comment by thvalidators** [comment]
> Still need to remove the `avatar.png` file outside of your validator directory. I was not able to find your `terravaloper` address, `terravaloper1uyu9sx8q5lmsdrj4t8w0unvd2u2uudq2kwpuxu`, on Mainnet or Classic. Can you confirm that this address is correct? On which network are you launching? Thanks!

Hi terra6  please advice how can i find my terravaloper
it come from  terra address or public key
also terravalconspub key
thanks in advance

**Comment by terran6** [comment]
> > Still need to remove the `avatar.png` file outside of your validator directory. I was not able to find your `terravaloper` address, `terravaloper1uyu9sx8q5lmsdrj4t8w0unvd2u2uudq2kwpuxu`, on Mainnet or Classic. Can you confirm that this address is correct? On which network are you launching? Thanks!
> 
> Hi terra6 please advice how can i find my terravaloper it come from terra address or public key also terravalconspub key thanks in advance

Hi!  I would check out our docs site for more information on registering your validator:

https://docs.terra.money/full-node/manage-a-terra-validator/set-up-validator

I am unsure about what steps you have followed so far, so it would be best if you could find out what needs to be done from the docs website.  Let me know if you can't find your answer here.

**Comment by thvalidators** [comment]
> > > Still need to remove the `avatar.png` file outside of your validator directory. I was not able to find your `terravaloper` address, `terravaloper1uyu9sx8q5lmsdrj4t8w0unvd2u2uudq2kwpuxu`, on Mainnet or Classic. Can you confirm that this address is correct? On which network are you launching? Thanks!
> > 
> > 
> > Hi terra6 please advice how can i find my terravaloper it come from terra address or public key also terravalconspub key thanks in advance
> 
> Hi! I would check out our docs site for more information on registering your validator:
> 
> https://docs.terra.money/full-node/manage-a-terra-validator/set-up-validator
> 
> I am unsure about what steps you have taken so far, so it would be best if you could find out what needs to be done from the docs website. Let me know if you can't find your answer here.

Hi terra6 I have  change to it to right one
Thanks

**Comment by thvalidators** [comment]
> Please remove the logo, outlined in red, as it is outside of your validator directory. The two logo files in orange seem to be the same image, please choose one and delete the other.
> 
> duplicate_logos

Deleted

**Pull request closed without merging**
