### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by LUXPayband**
Please validate the following.

profile.json
READ.ME.md

### CODE REVIEW

**Review by terran6 — CHANGES_REQUESTED** [review]
Looks good.  Just replace the `logo.png` inside of your validator directory with the `logo.png` outside of your directory.  You shouldn't have any files outside of your designated directory.  Thanks!

**Comment by LUXPayband** [comment]
Delete the existing logo.png inside of our validator directory? Add logo.png inside our validator directory via add file?

**Comment by terran6** [comment]
> Delete the existing logo.png inside of our validator directory? Add logo.png inside our validator directory via add file?

@LUXPayband The current `logo.png` file in your validator directory, shown in the orange boxes, does not seem to be rendering.  The `logo.png` file outside of your directory does seem to be showing your actual logo, so you can just replace the `logo.png` in the orange box below which is not rendering with the `logo.png` file in the red box which is showing your actual logo, but is outside of your validator directory.

Screen Shot 2022-11-01 at 10 00 51 AM

**Comment by LUXPayband** [comment]
Complete. Please review and validate. Thank you for your work,

profile.json
READ.ME.md
LX.png

Respectfully, 

The LUX Payband Team

**Comment by terran6** [comment]
> Complete. Please review and validate. Thank you for your work,
> 
> profile.json READ.ME.md LX.png
> 
> Respectfully,
> 
> The LUX Payband Team

Please delete the `logo.png` file outside of your validator directory.

Screen Shot 2022-11-01 at 11 50 56 AM

**Comment by LUXPayband** [comment]
Being tidy is paramount. Done.

Thank you.

**Review by terran6 — APPROVED** [review]
🚀

**Comment by LUXPayband** [comment]
Thank you again for your attention and assistance. Is there a time frame before LUX Blockchain Validators is listed on the Terra Validator Directory? 

_NOTE: Validators that have not yet put up a profile are hidden. Get the full list of validators [here]

Respectfully,

The LUX Payband Team

**Comment by terran6** [comment]
> Thank you again for your attention and assistance. Is there a time frame before LUX Blockchain Validators is listed on the Terra Validator Directory?
> 
> _NOTE: Validators that have not yet put up a profile are hidden. Get the full list of validators [here]
> 
> Respectfully,
> 
> The LUX Payband Team

@LUXPayband I am able to view your information after searching for your name while connected to LocalTerra:

image

**Comment by LUXPayband** [comment]
Thank you. However, on the Github Validator Directory. 
https://github.com/LUXPayband/validator-profiles

Also, we are still listed as a blue ball with no verification check. How do we go about getting those modicums of verification Complete?

Respectfully,

LUX Payband Team

**Comment by terran6** [comment]
> Thank you. However, on the Github Validator Directory. https://github.com/LUXPayband/validator-profiles
> 
> Also, we are still listed as a blue ball with no verification check. How do we go about getting those modicums of verification Complete?
> 
> Respectfully,
> 
> LUX Payband Team

@LUXPayband You can add yourself to the list on the README if that is what you are asking.
You should have your verification check soon, I will make sure that there aren't any issues on our end.

**Pull request merged**
