### PR TITLE
please add validator profile for terra2

### PR DESCRIPTION
**Pull request by awsdataarchitect**
It would be awesome if you could invite me to the validator discord: infablogger#5744

### CODE REVIEW

**Comment by Jared-TFL** [comment]
This repo isn’t for 2.0 profiles. the 2.0 repo doesn’t exist yet.

**Comment by awsdataarchitect** [comment]
sure, keep us updated once new repo is setup..is discord open for new validators @Jared-TFL

**Comment by awsdataarchitect** [comment]
@Jared-TFL Is this being used for terra2? Also when is Terra classic new validator reopening ? Can you send us discord invite please

**Comment by Jared-TFL** [comment]
Yep, repo for both now

**Pull request closed without merging**
