### PR TITLE
Tezro

### PR DESCRIPTION
**Pull request by MikeVini**
New Profile

### CODE REVIEW

**Review by terran6 — CHANGES_REQUESTED** [review]
Profile looks good.  Unsure about the reason for including the **.idea** folder.  Could you delete the folder and contents?  Thanks.

**Comment by MikeVini** [comment]
> Profile looks good. Unsure about the reason for including the **.idea** folder. Could you delete the folder and contents? Thanks.

Yes, of course. I deleted

**Review by terran6 — APPROVED** [review]

**Comment by MikeVini** [comment]
Hi @terran6, how are you? We have not been added to the main list of validators and have not yet received a checkmark in  Terra Station. Did we not provide some data?

**Comment by terran6** [comment]
Hey, @MikeVini.  Just made an update and you should be seeing a checkmark here soon.  Let me know if it isn't updated by tomorrow.

**Comment by MikeVini** [comment]
Hi, @terran6! We still haven't received the checkmark :(

**Comment by terran6** [comment]
@MikeVini, I have done some troubleshooting and was unable to find the source of the issue.  I will be updating you soon on next steps to get the checkmark included.  Sorry for the delay.

**Comment by terran6** [comment]
@MikeVini, Tezro is currently in "Inactive" status.  As soon as the status is updated to "Active", you should have the checkmark visible.

**Comment by MikeVini** [comment]
Oh, I didn't even think about it, thank you very much =)

**Pull request merged**
