### PR TITLE
CryptoKings Validator

### PR DESCRIPTION
**Pull request by Panvasi**

### CODE REVIEW

**Comment by Panvasi** [comment]
@terran6 :)

**Review by terran6 — CHANGES_REQUESTED** [review]
Hey @Panvasi.  As stated before it may be best to delete the `validators/terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27` directory if the old validator is no longer going to be utilized.  

Let me know if you have any questions or concerns.  

Thanks!

**Comment by Panvasi** [comment]
done @terran6

**Comment by terran6** [comment]
> done @terran6

@Panvasi Great!  Now just merge `main` into this branch and we can get rid of the directory in this branch before we merge.

**Comment by Panvasi** [comment]
ready @terran6

**Review by terran6 — APPROVED** [review]
🚀

**Comment by Panvasi** [comment]
<3

**Pull request merged**
