### PR TITLE
CryptoKings Validator

### PR DESCRIPTION
**Pull request by Panvasi**
terravaloper1urzzga0tjwthu5aejujtgmh4kcvvpj87vk45rz

Network: Columbus-5

### CODE REVIEW

**Review by terran6 — CHANGES_REQUESTED** [review]
It seems as though the README files are mixed up.  As the README in the `validators/terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27` validator directory refers to the `terravaloper1urzzga0tjwthu5aejujtgmh4kcvvpj87vk45rz` address and vice versa.  

Also, it seems as though the validator corresponding to the `terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27` address still retains the name `Athens Project` when searched on the `Mainnet` network at https://finder.terra.money/

Let me know if you have any questions or concerns.  Thanks!

**Review by Panvasi — COMMENTED** [review]
Correct

**Comment by Panvasi** [comment]
Athens project don't exist anymore

**Comment by terran6** [comment]
> Athens project don't exist anymore

Cool, so typically validators reference their terravaloper address in the README to match the terravaloper address of their validator directory.  You'd like to keep the `validators/terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27/README.md` to reference `terravaloper1urzzga0tjwthu5aejujtgmh4kcvvpj87vk45rz` and vice versa?

image

**Comment by Panvasi** [comment]
Updated README.MD 
we must change also the folder name to: terravaloper1urzzga0tjwthu5aejujtgmh4kcvvpj87vk45rz

image

**Comment by terran6** [comment]
@Panvasi If AthensProject does not exist anymore and will not be replaced, maybe that validator directory should be deleted.

**Comment by Panvasi** [comment]
ok i close this pull request and create new one

**Pull request closed without merging**
