### PR TITLE
Edit JT Stakers profile

### PR DESCRIPTION
**Pull request by Jackson-DKMG**
- new validator profile for a running node (Columbus & Bombay)

### CODE REVIEW

**Comment by Jared-Warn** [comment]
approved

**Comment by Jared-Warn** [comment]
this looks like an add not an edit

**Comment by Jackson-DKMG** [comment]
My bad, it should have been an 'add' instead of an 'edit' indeed.

Thanks.

**Comment by Jared-Warn** [comment]
got it, should see checkmark in about 2 days

**Pull request merged**
